
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */

public class MenuLogin extends javax.swing.JFrame {
    
    /**
     * Creates new form MenuUtama
     */
    PembeliLogin a = new PembeliLogin();
    
    
    //suara sound = new suara();
    
    private void CekLogin(){
        try{
            if(txtinemail.getText().equals("") ||txtinpass.getText().equals("")){
                //sound.sfx("D:\\Netbin\\wow.wav");
                JOptionPane.showMessageDialog(rootPane, "DataTidak Boleh Kosong", "Pesan", JOptionPane.ERROR_MESSAGE);
                inemail.requestFocus();
                HapusLayar();
            }else{
                String sql = ("SELECT * FROM pembeli WHERE email ='"+txtinemail.getText()+"' AND Password ='"+String.valueOf(txtinpass.getText())+"'");
                java.sql.Connection conn = (java.sql.Connection)KoneksiDB.koneksi();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql);
                if(res.next()){
                    //sound.sfx("D:\\Netbin\\asiap.wav");
                    a.setp_email(txtinemail.getText());
                    this.dispose();
                    new MenuUtama().setVisible(true);
                    
                }else{
                    //sound.sfx("D:\\Netbin\\wow.wav");
                    JOptionPane.showMessageDialog(rootPane, "UserName dan Password Salah atau Akun Belum Terdaftar", "Pesan",JOptionPane.ERROR_MESSAGE);
                    HapusLayar();
                }
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    //private void kosongkan_form(){
    //    txtinemail.setText(null);
    //    txtinpass.setText(null);
    //}
    
    private void HapusLayar(){
        txtinemail.setText("");
        txtinpass.setText("");
        inemail.setEnabled(true);
        inpass.setEnabled(true);
    }
    
    public MenuLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        inemail = new javax.swing.JLabel();
        inpass = new javax.swing.JLabel();
        txtinemail = new javax.swing.JTextField();
        txtinpass = new javax.swing.JPasswordField();
        masukbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        daftarbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RUMAH KITA");

        inemail.setText("Email");

        inpass.setText("Password");

        txtinemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinemailActionPerformed(evt);
            }
        });

        txtinpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinpassActionPerformed(evt);
            }
        });

        masukbutton.setText("Masuk");
        masukbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukbuttonActionPerformed(evt);
            }
        });

        jLabel2.setText("Atau");

        daftarbutton.setText("Daftar");
        daftarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inemail)
                    .addComponent(inpass))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtinpass)
                    .addComponent(txtinemail, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 201, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(masukbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(daftarbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(296, 296, 296))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inemail)
                    .addComponent(txtinemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inpass)
                    .addComponent(txtinpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(masukbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(daftarbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtinemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinemailActionPerformed

    private void daftarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarbuttonActionPerformed
        // TODO add your handling code here:
        //sound.sfx("D:\\Netbin\\asiap.wav");
        pembeliForm n = new pembeliForm();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_daftarbuttonActionPerformed

    private void masukbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukbuttonActionPerformed
        // TODO add your handling code here:
        CekLogin();
    }//GEN-LAST:event_masukbuttonActionPerformed

    private void txtinpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton daftarbutton;
    private javax.swing.JLabel inemail;
    private javax.swing.JLabel inpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton masukbutton;
    private javax.swing.JTextField txtinemail;
    private javax.swing.JPasswordField txtinpass;
    // End of variables declaration//GEN-END:variables
}
